export const SN_STOCK = 'stock'
export const STOCK_PRDCTS_BY_FACLTY_BLK_UPDATED = SN_STOCK + '/PRDCTS_BY_FACLTY_BLK_UPDATED'
export const STOCK_PREODR_AVLBLTY_BLK_UPDATED = SN_STOCK + '/PREODR_AVLBLTY_BLK_UPDATED'